package com.udaan.snorql.extensions.performance.models

import com.udaan.snorql.extensions.performance.PerformanceEnums
import com.udaan.snorql.framework.annotations.SnorqlColumnName
import com.udaan.snorql.framework.models.IMetricResult
import com.udaan.snorql.framework.models.MetricInput
import com.udaan.snorql.framework.models.MetricPeriod

/**
 * Model class to hold the XML plan generated by the SQL Query Engine
 * @property xmlPlan: XML Plan generated by the engine
 */
data class QueryPlanXMLModelDTO(
    @SnorqlColumnName("Microsoft SQL Server 2005 XML Showplan")
    val xmlPlan: String
)

data class QueryPlanXMLInput(
    override val metricId: String = PerformanceEnums.QUERY_PLAN_XML.getId(),
    override val metricPeriod: MetricPeriod,
    override val databaseName: String,
    val query: String
): MetricInput()

data class QueryPlanXMLResult(val queryList: List<QueryPlanXMLModelDTO>) : IMetricResult()
