name: Github Release

on:
  push:
    branches:
      - add-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: "contains(github.event.head_commit.message, '[[maven-release-plugin] prepare release snorql-]')"

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo ${{ github.actor }}
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/target/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.RELEASE_VERSION }}"
          bodyFile: "v${{ env.RELEASE_VERSION }}.md"
          commit: add-ci-cd