name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - releasing-to-nexus
    paths:
      - 'doc/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Build
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-args: "clean install"

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: doc/mkdocs.yml
