name: Readme

on:
  push:
    paths:
      - 'doc/**'

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install

      - name: Run script file
        run: |
          chmod +x ./scripts/populate-readme.sh
          ./scripts/populate-readme.sh
        shell: bash

      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: currentref

      - name: Push to master
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.currentref.outputs.branch }}